# Generated by Django 5.1.3 on 2024-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.CharField(max_length=5),
        ),
    ]
