# Generated by Django 5.1.3 on 2024-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_adoption_status_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'scheduled'), ('CANCELLED', 'cancelled'), ('PENDING', 'pending')], default='PENDING', max_length=10),
        ),
    ]
