# Generated by Django 5.1.3 on 2024-11-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
