# Generated by Django 5.1.3 on 2024-12-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_adoption_adoption_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cat')),
            ],
        ),
    ]
