# Generated by Django 5.1.3 on 2024-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adoption',
            name='children_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='adoption',
            name='other_pets_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
