# Generated by Django 5.1.3 on 2024-12-10 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_adoption_household_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'scheduled'), ('CANCELLED', 'cancelled'), ('PENDING', 'pending'), ('COMPLETED', 'completed')], default='PENDING', max_length=10),
        ),
    ]
