# Generated by Django 5.1.3 on 2024-12-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_customer_user_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
