# Generated by Django 5.1.3 on 2024-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'scheduled'), ('COMPLETED', 'completed')], default='SCHEDULED', max_length=10),
        ),
    ]
