# Generated by Django 5.1.3 on 2024-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_example', '0002_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='bank_example.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
