# Generated by Django 5.1.3 on 2024-11-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_example', '0003_student_courses_alter_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_example.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_example.student')),
            ],
        ),
    ]
