# Generated by Django 5.1.3 on 2024-11-19 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_example', '0004_remove_student_courses_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_person', to='bank_example.familyperson')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_person', to='bank_example.familyperson')),
            ],
        ),
    ]
